---
- hosts: test
  remote_user: fih
  sudo: True
  vars:
   logfile: /var/log/nginx/access1.log
  tasks:
  - name: ensure nginx is at the latest version
    yum: name={{ item }} state=latest
    with_items:
      - nginx
      - libselinux-python

  - name: rewrite the nginx config
    template: src=template/nginx.j2 dest=/etc/nginx/nginx.conf

  - name: ensure nginx is running (and enable it at boot)
    service: name=nginx state=started enabled=yes
